# Generated by Django 3.2.4 on 2021-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_img',
            field=models.ImageField(default='test', upload_to='displays'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag'),
        ),
    ]
