# Generated by Django 3.2.4 on 2021-07-01 00:42

import autoslug.fields
from django.db import migrations


def generate_slugs(apps, schema_editor):
    TagModel = apps.get_model('blog', 'Tag')
    for row in TagModel.objects.all():
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_categories_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='tag', unique=True),
        ),
        migrations.RunPython(
            generate_slugs,
            reverse_code=migrations.RunPython.noop
        )
    ]
