# Generated by Django 3.2.4 on 2021-07-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210703_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name_plural': 'IP Addresses'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='ip_list',
        ),
        migrations.AddField(
            model_name='post',
            name='ips',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.IPAddress'),
        ),
    ]
